# Generated by Django 5.1.6 on 2025-02-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thread_id', models.BigIntegerField()),
                ('board', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=15)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['board', 'thread_id'], name='webarchive__board_329460_idx')],
                'unique_together': {('board', 'thread_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=5)),
                ('message_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('has_audio', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webarchive.thread')),
            ],
            options={
                'indexes': [models.Index(fields=['board', 'thread_id', 'message_id'], name='webarchive__board_18b419_idx')],
                'unique_together': {('board', 'thread_id', 'message_id')},
            },
        ),
    ]
