# Generated by Django 5.1.6 on 2025-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0002_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(default='open', max_length=15),
        ),
    ]
