# Generated by Django 5.1.6 on 2025-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0003_alter_thread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.IntegerField(default=0),
        ),
    ]
