# Generated by Django 5.1.6 on 2025-02-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0004_thread_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
