# Generated by Django 5.1.6 on 2025-02-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0005_message_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
