# Generated by Django 5.1.6 on 2025-02-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0006_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='Long_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
