# Generated by Django 5.1.6 on 2025-02-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webarchive', '0007_board_long_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Long_name',
            new_name='long_name',
        ),
    ]
